services:
  classification_service:
    command: ["npm", "run", "start:dev"]
    develop:
      watch:
        - action: sync
          path: ./mss/ClassificationService
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./mss/ClassificationService/package.json