apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgdata-auth-pv
spec:
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/var/lib/auth/postgres"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgdata-register-pv
spec:
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/var/lib/register/postgres"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgdata-classification-pv
spec:
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/var/lib/classification/postgres"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgdata-image-pv
spec:
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/var/lib/image/postgres"