import dotenv from 'dotenv';

dotenv.config();

// RABBITMQ_HOST=rabbitmq
// RABBITMQ_PORT=5672
// RABBITMQ_MANAGEMENT_PORT=15672
// RABBITMQ_DEFAULT_USER=rabbitmq
// RABBITMQ_DEFAULT_PASS=rabbitmq


export const {
  PORT,
  DATABASE_HOST,
  DATABASE_PORT,
  DATABASE_USER,
  DATABASE_PASSWORD,
  DATABASE_NAME,
  REDIS_HOST,
  REDIS_PORT,
  REDIS_PASSWORD,
  RABBITMQ_HOST,
  RABBITMQ_PORT,
  RABBITMQ_USER,
  RABBITMQ_PASSWORD,
  SERVICE_NAME,
  JWT_SECRET,
  ENCRYPTION_KEY,
  NODE_ENV
} = process.env;


